### ISSUE TITLE
Tototaly broken json file - tool don't detect any errors

### ISSUE THREAD

**Issue by CudaText-addons** [jacksmith15/jsonschema-lint#1]
```
{{{
  "ttt": "test"
  "eee::
}
```

**Comment by jacksmith15** [comment]
@CudaText-addons please provide steps to reproduce your issue. 

I cannot reproduce the issue, but I cannot be sure I am running the same steps as you. For example, I do not know if the example you have provided is a broken schema or instance.

Here's what I did to try to reproduce:

`instance.json`:

```
{{{
  "ttt": "test"
  "eee::
}
```

and `schema.json`:

```json
{}
```

Then the following command:

```bash
jsonschema-lint --schema schema.json instance.json
```

Produces the following output:

```
instance.json:3:3:3:4: Unclosed string at line 3, column 3
```

I think this is the correct behaviour.

**Comment by CudaText-addons** [comment]
I just missed all schema.json files on disk, I run tool with some random broken json file in random dir. in this case it must not work?

**Comment by jacksmith15** [comment]
I'm not certain I understand what you are saying, but, If there are no schemas to validate against, the tool will do nothing. This is the expected behaviour. Compare it to running a test suite which contains no tests - one would expect that to pass.
